### ISSUE TITLE
The old xml was better 

### ISSUE THREAD

**Issue by EC-O-DE** [WhitefangGreytail/WG_RealisticCitySkylines#17]
The old xml was better and easier to modify than this new space_pp= and level_height=. 

I got to stop using this mod :/

Too bad popbalancemod is not configurable.

**Comment by WhitefangGreytail** [comment]
PopBalanceMod not being configurable (and the creator being away) is the reason why I am carrying on the work. So was julianay.

Then it took a life of it's own. The change in the XML is to accomodate building height so that different themes can work without people having to change the XML for different themes. It adds that realism when they look the the building and the panel will show a workers that will be relative to each other based on size, not just land space. To make this realism happen, I had to add in the space per person and the level height.

I am sorry if this makes it harder for you to modify the values.

I have placed v3.3 in the archive for you. Unsubscribe and place the dll file into the old location, the game will still find it. You can also rename the xml.ver2 to get your old values back.

The archive is here. https://github.com/WhitefangGreytail/WG_RealisticCitySkylines/tree/master/Archive

**Comment by EC-O-DE** [comment]
Thanks for the archive <3

**Comment by EC-O-DE** [comment]
Hey could you add game defaults to the archive section, much appreciated :)

**Comment by WhitefangGreytail** [comment]
It's been added as a zip archive.

**Comment by EC-O-DE** [comment]
Thank you very much <3
